// Auto-generated from CONTENT.md — do not edit directly.
// To update labels or order, use the admin UI or edit CONTENT.md.

const LABELS = [
  { filename: "IMG_6386.jpeg", title: "The Last Bright Conversation", desc: "Acrylic on Canvas, 60\" x 48\"" },
  { filename: "8923CF4A-CF82-4566-BD82-ED9D887A63E9.jpeg", title: "The Last Bright Conversation", desc: "Acrylic on Canvas, 60\" x 48\"" },
  { filename: "IMG_6046.jpeg", title: "Helix Becoming", desc: "Acrylic on Canvas, 24\" x 48\"" },
  { filename: "IMG_6201.jpeg", title: "When the River Became Two", desc: "Acrylic on Canvas, 36\" x 36\" Diptych" },
  { filename: "IMG_6410-2.jpeg", title: "Too Wild for Still Water", desc: "Acrylic on Canvas, 60\" x 48\"" },
  { filename: "IMG_6371.jpeg", title: "Too Wild for Still Water", desc: "Acrylic on Canvas, 60\" x 48\"" },
  { filename: "3F6DE66B-B2C7-4032-A27A-9E9A2D109C27.jpeg", title: "Paper Planes / No Borders", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "image (3).png", title: "Paper Planes / No Borders", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "IMG_0725.heic", title: "Hidden Princess (Collab With Carter Hackett", desc: "Acrylic on Canvas, 48\" x 24\"" },
  { filename: "IMG_6370.jpeg", title: "Hidden Princess (Collab With Carter Hackett", desc: "Acrylic on Canvas, 48\" x 24\"" },
  { filename: "IMG_6157.heic", title: "Emerald Audrey", desc: "Acrylic on Canvas, 40\" x 60\"" },
  { filename: "IMG_6376.jpeg", title: "Emerald Audrey", desc: "Acrylic on Canvas, 40\" x 60\"" },
  { filename: "IMG_6418.jpeg", title: "Fire Mother", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "IMG_6379-2.jpeg", title: "Fire Mother", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "IMG_6346.jpeg", title: "Wildflowers Don't Care Where They Grow", desc: "Acrylic on Canvas, 36\" x 36\"" },
  { filename: "62009220-FFE9-4148-9A41-C63545910216.png", title: "Wildflowers Don't Care Where They Grow", desc: "" },
  { filename: "FullSizeRender.heic", title: "Cobalt River Canyon", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "IMG_3568.jpeg", title: "Cobalt River Canyon", desc: "Acrylic on Canvas, 60\" x 40\"" },
  { filename: "IMG_3473.jpeg", title: "Verdant Arc", desc: "Acrylic on Canvas, 24\" x 36\"" },
  { filename: "IMG_3471.jpeg", title: "Verdant Bloom", desc: "Acrylic on Canvas, 24\" x 36\"" },
  { filename: "IMG_0570.jpeg", title: "The Secret Red", desc: "Alcohol Ink on Yupo Paper, 4\" x 6\"" },
  { filename: "AD21225A-EB38-4FE3-884B-A01928051BA6_1_105_c.jpeg", title: "The Secret Red", desc: "hol Ink on Yupo Paper, 4\" x 6\"" },
  { filename: "IMG_6219.jpeg", title: "Etude #8", desc: "Acrylic on Canvas, 14\" x 11\"" },
  { filename: "IMG_4195.jpeg", title: "Upon Reflection", desc: "Acrylic on Canvas, 14\" x 11\"" },
  { filename: "IMG_9358.jpeg", title: "Strata I - III", desc: "Paper Series" },
  { filename: "IMG_6221.jpeg", title: "Strata I - III", desc: "Paper Series" },
  { filename: "IMG_5991.jpeg", title: "Greenland's House", desc: "Acrylic Ink on Paper, 8\" x 10\"" },
  { filename: "IMG_0861.jpeg", title: "Crimson Drift", desc: "Acrylic on Canvas, 36\" x 36\"" },
  { filename: "IMG_6344.jpeg", title: "Simple Song", desc: "Alcohol Ink on Yupo Paper" },
  { filename: "IMG_6350.jpeg", title: "All of Our Days", desc: "Alcohol Ink on Yupo Paper" },
  { filename: "IMG_6369.jpeg", title: "Triana District", desc: "Acrylic on Paper" },
  { filename: "IMG_3622.jpeg", title: "Catalonian Dream", desc: "Ink on Paper" },
  { filename: "IMG_4869.jpeg", title: "Untitled #3", desc: "Ink on Paper Collage" },
  { filename: "22C10F17-3C11-49C7-8E31-3913FC97D56E_1_105_c.jpeg", title: "Saturday on the F", desc: "Photo Collage" },
  { filename: "IMG_6452.jpeg", title: "Paper Tiles", desc: "Cyanotype on Paper, 20\" x 14\"" },
];
